name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  phpunit-test:
    name: PHP 8.0 PHPUnit
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: dbname_test
          MYSQL_USER: dbuser
          MYSQL_PASSWORD: dbpass
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        extensions: mbstring, intl, pdo_mysql, fileinfo
        coverage: none

    - name: Composer install
      run: |
        composer install
        composer run-script post-install-cmd --no-interaction

    - name: Run PHPUnit
      run: |
        cp -f config/.env.default config/.env
        vendor/bin/phpunit

  coding-standard:
    name: Coding Standard
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, intl
        coverage: none

    - name: Composer install
      run: composer install

    - name: Run PHP CodeSniffer
      run: composer cs-check

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, intl
        coverage: none

    - name: Composer install
      run: composer install

    - name: Run phpstan
      run: vendor/bin/phpstan
